baseURL: "https://www.prestashop-project.org/"
languageCode: "en-us"
defaultContentLanguage: "en"
languages:
  en:
    title: "PrestaShop Project - Open Source e-Commerce platform"
    languageCode: "en-us"
    languageName: "English"
    weight: 1
  it:
    title: "PrestaShop Project - Piattaforma e-Commerce Open Source"
    languageCode: "it-it"
    languageName: "Italiano"
    weight: 2

theme: "ps-org-theme"
enableGitInfo: true
enableRobotsTXT: true
googleAnalytics: "G-KK4ZZ04Y2S"

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: github
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1
